language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: java-markdown-blog
    token:
      secure:
        - echo "$SONAR_TOKEN"

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY

before_install:
  - mvn clean
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jdk

script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml

after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
