spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false