server:
  error.whitelabel.enabled: false

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: true
  thymeleaf:
    cache: true
  security:
    user:
      name: user
      password: ${USER_PASSWORD}
      roles: editor
  messages:
    basename: messages/messages

social:
  links:
    linkedin: https://www.linkedin.com
    github: https://www.github.com
    twitter: https://www.twitter.com